apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: backend-svc
  name: backend-svc
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: backend-svc
