apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend-svc
  name: frontend-svc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: frontend-svc
