apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend-svc
  name: frontend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-svc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o ./k8s
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/ai-aplication-default: "true"
        io.kompose.service: frontend-svc
    spec:
      containers:
        - image: frontend:dev
          name: frontend-svc
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
      restartPolicy: Always
